### ISSUE TITLE
[Lyrics correction] - "Ye Duniya Gol Hai" from "Chaudhvin Ka Chand"

### ISSUE THREAD

**Issue by sramabhadran** [v9y/giit#110]
Song's giitaayan URL: https://www.giitaayan.com/viewisbsong.asp?id=2242

Metadata (statistics) corrections, if any: none

Please write the corrected lyrics below (in ITRANS or common Roman convention):

ye duniyaa gol hai, uupar se khol hai
/// Rafi distinctly says Kol (kh but with the dot underneath)...I don't know what it means but that's what I hear

andar jo dekho pyaare bilakul polam-pol hai
ye duniyaa gol hai

kitane hii duniyaa vaale, rahate hai.n gheraa Daale
/// Should be "jitne hai.N", then "phirte hai.N jholii Daale"

koii muraad maa.Nge, koii aulaad maa.Nge
koii muhabbat chaahe, koii huquumat chaahe
/// There is another Johnny Walker line here, but can't exactly decipher it...

sabake gale me.n bhaiyyaa aramaano.n kaa Dol hai
/// "armaanon ka DHol", no? Sounds like it.

ye duniyaa gol hai   ...

rupaiyya paisaa na maa.Nguu.N, sonaa chaa.Ndii na maa.Nguu.N
/// Re-arrange to "chaa.Ndi sonaa na maa.Nguu.N, rupaiyya paisaa na maa.Nguu.N"

kapa.Daa lattaa na maa.Nguu.N, gho.Daa gaa.Dii na maa.Nguu.N
/// kholii banglaa na maa.Nguu.N, kapa.Daa lattaa na maa.Nguu.N
/// Missing line - "gho.Daa gaa.Dii na maa.Nguu.N, kurtaa dhotii na maa.Nguu.N"

paravar_digaar mere, usakaa diidaar de de
ek foto kaa savaal hai baabaa, bol ab tak nahii.n milaa
/// Something like that but double-check?

paravar_digaar mere, usakaa diidaar de de
jaldii milaa de merii duniyaa Daa.NvaaDol hai
ye duniyaa gol hai   ...

are baap re, ye kahaa.N se, Tyuun badalo
mere maulaa bulaa le madiine ise
/// first time he says "mujhe"

lage mauke pe aane pasiine mujhe
/// "lage maut ke aane pasiine mujhe"
/// then, when the cop walks by it's "mere maulaa bulaa le madiine ise", so the cop corrects him...
    - ise nahii.n, baabaa, mujhe
achchhaa betaa, la.nbii umar ho jaldii se la.nbe ho jaao
ye duniyaa gol hai   ...

**Comment by v9y** [comment]
I have updated the lyrics. 'Khol' (ख़ोल) is right - it means mask or cover. I have not included Johnny Walker's lines in the antaraas, because they are superfluous and I don't think are part of the song. I have, however, included the dialogue in the  concluding stanza in parentheses.
