### ISSUE TITLE
Marne Ki Duaaen Kyon Maangoon

### ISSUE THREAD

**Issue by sramabhadran** [v9y/giit#111]
Song's giitaayan URL: http://giitaayan.com/viewisbsong.asp?id=1155

Metadata (statistics) corrections, if any:

Please write the corrected lyrics below (in ITRANS or common Roman convention):

"ab aish ikaTThaa kashtii par" 

should be "ab aisii shikastaa kashtii par"

General comment: ITRANS "standardization" required for rest of lyrics.

**Comment by v9y** [comment]
Issue fixed. Sorry, it took this long. Apparently I missed the notification.

NTS: pull it in giitaayan.
