### ISSUE TITLE
[Lyrics correction] zahar detaa hai mujhe (submitted by Surajit Bose)

### ISSUE THREAD

**Issue by v9y** [v9y/giit#13]
Song's giitaayan URL: http://www.giitaayan.com/viewisbsong.asp?id=rmim0116

Please write the corrected lyrics below (in ITRANS or common Roman convention):

Hello,

Here's https://gaane.giitaayan.com/files/rmim0116.isb.txt with an additional stanza to the Bhupinder version. I don't know whether there's an extra stanza to the Asha version as well; I seem to remember hearing three stanzas in each but I can't recall any lyrics for the Asha version. Also a P-stats correction. I don't know why it's marked as non-film. The movie isn't in HFGK that I can find but the vinyl release says "From the Original Soundtrack" and has pictures of pretty people on it. 

- s

% ITRANS SONG # rmim0116; Created on Jan 26, 2004
% 
\startsong
\stitle{zahar detaa hai mujhe ko_ii davaa detaa hai}%
\film{Wohi Baat}%
\year{1977}%
\starring{Shabana Azmi, Parikshit Sahani, Amol Palekar}%
\singer{Asha/ Bhupinder}%
\music{Jaidev}%
\lyrics{Naqsh Lyallpuri}%
% 
% Contributor: Arunabha S Roy
% Transliterator: Arunabha S Roy
% Date: 14 Sep 2003
% Series: GEETanjali
% Credits:     Surajit A. Bose
% Comments: Two versions of this song: one by Asha and the other by Bhupinder
% generated using giitaayan
%
\printtitle
#indian
%
## Asha version ##

zahar detaa hai mujhe ko_ii davaa detaa hai
jo bhii milataa hai mere Gam ko ba.Dhaa detaa hai

kyo.n sulagatii hai.n mere dil me.n puraanii yaade.n
kaun bujhate hu_e sholo.n ko hawaa detaa hai

haal ha.Ns-ha.Ns_ke bulaataa hai kabhii baaho.n me.n
kabhii maazii mujhe ro-roke sadaa detaa hai

##Bhupinder version ##

zahar detaa hai mujhe ko_ii davaa detaa hai
jo bhii milataa hai mere Gam ko ba.Dhaa detaa hai

kisii hamadam kaa sar-e-shaam judaa ho jaanaa
nii.nd jalatii hu_ii.n aa.Nkho.n se u.Daa detaa hai

vaqt hii dard ke kaa.NTo.n pe sulaa_e dil ko
vaqt hii dard kaa ahasaas miTaa detaa hai

pyaas itanii hai merii ruuh kii gaharaaii me.n
ashk girataa hai to daaman ko jalaa detaa hai
%
#endindian
\endsong
%

**Comment by v9y** [comment]
This file is now on github and should be edited here. The path is: https://v9y.github.io/giit/docs/rmim0116.isb.txt

**Comment by v9y** [comment]
@morosebose : Would you want to fix and push this?

**Comment by morosebose** [comment]
Yup, will do later today. Thanks for migrating the files!

**Comment by morosebose** [comment]
Done, pending review by boss-man (≠ Bose-man)

**Comment by v9y** [comment]
Thanks @morosebose!
