### ISSUE TITLE
HiTrans does not handle escape chars

### ISSUE THREAD

**Issue by morosebose** [v9y/giit#69]
The HiTrans interface on the left-hand sidebar of the giitaayan page does not respect the hash marks as escape chars, and tries to convert even ##this text## into Nagari. 

If there is a desire to maintain backward compatibility with older iTrans specs, then \backslash and {curly braces} should also be correctly handled by that interface, but that's a "nice to have".

Right now there is no public-facing interface that works seamlessly; songs generated using old ISB specs and including \backslash,  ##english words## etc. don't render correctly on the HiTrans interface, and HiTrans-spec songs including "Kh" for "K",  eschewing the \backslash, etc. don't render correctly on older iTrans conversion interfaces. This makes me sad 😢

**Comment by v9y** [comment]
Yes, I had plans to add the ## escape in the Nagari conversion mechanism for songs. Thanks for opening the issue.

This is not so much as HiTrans issue per se, but rather an ISB schema translation issue.

**Comment by v9y** [comment]
Just checked. It looks like I had already enabled ##escape feature on the Nagari conversion of songs and it works there. 
For example, http://www.giitaayan.com/viewisbsong.asp?id=400

You are right in that HiTrans tool itself doesn't do that but as I said, I think the using ## for escaping English characters is more of an ISB schema feature that HiTrans.

**Comment by morosebose** [comment]
> Just checked. It looks like I had already enabled ##escape feature on the Nagari conversion of songs and it works there.

Right, I knew that. Sorry, I should have said so when I opened the issue. The issue is just regarding the public-facing HiTrans tool on the left hand sidebar of the giitaayan page.

**Comment by v9y** [comment]
Closing since it's already working for isb conversion.
