### ISSUE TITLE
[Lyrics correction] FITB Request: haal-chaal Thiik-Thaak hai (Submitted by Vijay Kumar K)

### ISSUE THREAD

**Issue by v9y** [v9y/giit#72]
Song's giitaayan URL: http://www.giitaayan.com/viewisbsong.asp?id=649

FITB - added the missing second stanza

haal chaal Thiik-Thaak hai, sab kuchh Thiik-Thaak hai
##B.A.## kiyaa hai, ##M.A.## kiyaa, lagataa hai vo bhii ai.nvai.n kiyaa
kaam nahii.n hai varanaa yahaa.N aap kii du_aa is sab Thiik-Thaak hai

aab-o-havaa vaa-vaa-vaa vaa-vaa-vaa
aab-o-havaa desh kii bahut saaf hai
kaayadaa hai, qaanuun hai, insaaf hai
allaah miyaa.N jaane koii jiye yaa mare
aadamii ko Kuun-vuun sab maaf hai
aur kyaa kahuu.N? chhoTii moTii chorii
rishvat_Korii detii hai apanaa guzaaraa yahaa.N 
aap kii du_aa se baakii Thiik-Thaak hai
haal chaal Thiik-Thaak hai ...

baazaaro.n ke bhaav
baazaaro.n ke bhaav?
baazaaro.n ke bhaav mere taa_uu se ba.De
makaano.n pe paga.Diivaale sasur kha.De
buDDhii bhuukh maratii nahii.n zi.ndaa hai abhii
koii in buzurgo.n se kaise la.De.n?
aur kyaa kahuu.n? roz koii miiTi.ng roz koii bhaashhaN
bhaashhaN pe raashan nahii.n hai yahaa.n
aap kii du_aa se baakii Thiik-Thaak hai
## very good ##
haal chaal Thiik-Thaak hai ...

gol-mol roTii kaa pahiyaa chalaa - 2
piichhe-piichhe chaa.Ndii kaa rupaiyaa chalaa 
roTii ko bechaarii to chiil le gayii (oh terii)
chaa.Ndii le mu.Nh kaalaa kauvaa chalaa
aur kyaa kahuu.N? maut kaa tamaashaa
chalaa hai betahaashaa, jiine kii furasat nahii.n hai yahaa.N 
aap kii du_aa se baakii Thiik Thaak hai 
##very good##
haal chaal Thiik-Thaak hai ...

**Comment by morosebose** [comment]
Checked the lyrics. Modified the file and created the commit.
