### ISSUE TITLE
[Lyrics correction] 4249: ham tere pyaar me.n (Submitted by Amarendra)

### ISSUE THREAD

**Issue by v9y** [v9y/giit#73]
Song's giitaayan URL: http://www.giitaayan.com/viewisbsong.asp?id=2336

From Amarendra R Nargundkar:
Corrections and additions to the song : http://www.giitaayan.com/viewisbsong.asp?id=2336. Birth Anniversary of Hasrat Jaipuri - April 15.

Updated lyrics:

ham tere pyaar me.n saaraa aalam kho baiThe hai.n, kho baiThe
tum kahate ho ki aise pyaar ko bhuul jaa_, bhuul jaa_o
ham tere pyaar me.n saaraa aalam

pa.Nchhii se chhu.Daakar usakaa ghar, tum apane ghar par le aa_e
ye pyaar kaa pi.nja.Daa man bhaayaa, ham jii bhar-bhar kar muskaa_e
jab pyaar hu_aa is pi.nja.De se, tum kahane lage aazaad raho
ham kaise bhulaa_e.N pyaar teraa, tum apanii zubaa.N se ye naa kaho
ab tumasaa jahaa.N me.n ko_ii nahii.n hai, ham to tumhaare ho baiThe
tum kahate ho ki aise pyaar ko bhuul jaa_, bhuul jaa_o
ham tere pyaar me.n saaraa aalam

is tere charan kii dhuul se hamane apanii jiivan-maa.Ng bharii
jab hii to suhaagan kahalaa_ii, duniyaa kii nazar me.n pyaar banii
tum pyaar kii su.ndar muurat ho, aur pyaar hamaarii puujaa hai
ab in charaNo.n me.n dam nikale, bas itanii aur tamannaa hai
ham pyaar ke ga.ngaajal se balamajii, tan-man apanaa dho baiThe
tum kahate ho ki aise pyaar ko bhuul jaa_, bhuul jaa_o
ham tere pyaar me.n saaraa aalam

sapano.n kaa darpan dekhaa thaa, sapano.n kaa darpan to.D diyaa
ye pyaar kaa aa.Nchal hamane to, daaman se tumhaare baa.Ndh liyaa
ye aisii gaa.NTh hai ulfat kii, jisako naa ko_ii bhii khol sakaa
tum aan base jab is dil me.n, dil phir to kahii.n naa Dol sakaa
o pyaar ke saagar, ham terii laharo.n me.n naav Dubo baiThe
tum kahate ho ki aise pyaar ko bhuul jaa_, bhuul jaa_o
ham tere pyaar me.n saaraa aalam

**Comment by morosebose** [comment]
Nice work by Amarendra. Updated file, pushed commit.
