### ISSUE TITLE
[Lyrics correction] 145: achchhaa unhe.n dekhaa hai (Submitted by Vijay Kumar K)

### ISSUE THREAD

**Issue by v9y** [v9y/giit#74]
Song's giitaayan URL: http://www.giitaayan.com/viewisbsong.asp?id=145

From Vijay Kumar K:
"FITB: Added one missing stanza and made other corrections"

Updated lyrics:

achchhaa unhe.n dekhaa hai biimaar huii aa.Nkhe.n
murjhaaii sii rahatii hai ghabaraaii sii rahatii hai.n
maashuuko.n kii mahafil me.n sharmaaii sii rahatii hai.n
kyaa jaane huaa kyaa hai patharaaii sii rahatii hai.n
achchhaa unhe.n dekhaa biimaar huii aa.Nkhe.n

shokhii bhii luTaa baiThii.n mastii bhii luTaa baiThii.n
uThatii hai na jhukatii hai.n kyaa rog lagaa baiThii.n
e yaar
kyaa rog lagaa baiThii.n ki biimaar huii aa.Nkhe.n
achchhaa unhe.n dekhaa biimaar huii aa.Nkhe.n

kis tarah haTe dar se vaadaa hai sitamagar se
kahatii hai lagan dil kii vo chal bhii chuke ghar se
hai faasalaa dam bhar kaa phir dekh samaa ghar kaa
vo hilane lagii chilaman vo pardaa-e-dar sarakaa
lo aa hii gayaa koii 
e yaar
lo aa hii gayaa koii lo chaar huii aa.Nkhe.n sarashaar huii aa.Nkhe.n
sarashaar huii aa.Nkhe.n
achchhaa unhe.n dekhaa biimaar huii aa.Nkhe.n

vo naqaab ruK se uThaae kyo.n
vo bahaar-e-husn luTaae kyo.n
sar-e-bazm jalvaa dikhaae kyo.n
tumhe.n a.Nkha.Diyo.n se pilaae kyo.n
ke vo apane nashe me.n chuur hai
jo nashe me.n chuur rahe sadaa
use terii haal kaa kyaa pataa
rahaa yuu.N hii dil kaa mu_aamalaa
magar usakii koii nahii.n Kataa
terii aa.Nkh kaa ye kasuur hai
aa.Nkho.n pe pa.Daa pardaa 
e yaar
aa.Nkho.n pe pa.Daa pardaa laachaar huii aa.Nkhe.n
achchhaa unhe.n dekhaa hai biimaar huii aa.Nkhe.n

hamane aaj ek Kvaab dekhaa hai Kvaab bhii laajavaab dekhaa hai
koii taabiir is kii batalaao raat ko aaftaab dekhaa hai
yaanii zi.ndaa sharaab dekhoge husn ko be-naqaab dekhoge
raat ko aaftaab dekhaa hai subah ko maahataab dekhoge
chaa.Ndanii me.n uThii ghaTaa jaise
dar-e-mayaKaanaa khul gayaa jaise
ye fasaanaa sahii hasii.n to hai
nashe me.n rach ga_ii adaa jaise

ko_ii tum saa bhii ho naa diivaanaa
tum haqiikat ko samajhe afasaanaa
chaa.Ndanii us kaa ra.ng zulf ghaTaa
aur aa.Nkhe.n hai.n jaise maikhaanaa
mayaKaane me.n pahu.Nchii to 
e yaar
mayaKaane me.n pahu.Nchii to mayaKvaar huii aa.Nkhe.n
mayaKvaar huii aa.Nkhe.n, gul_naar huii aa.Nkhe.n
achchhaa unhe.n dekhaa hai biimaar huii aa.Nkhe.n

sunate hai.n us dar pe jaake sar jhukaanaa manaa hai
sar jhukaa bhii le.n agar to baiTh jaanaa manaa hai
baiTh bhii jaaye.n kisii kone me.n to kyaa faayadaa?
jis taraf vo ho.n udhar nazare.n uThaanaa manaa hai
aur agar nazare.n uThe.n to dard-e-dil ko kyaa kare.n?
dard-e-dil kaise miTe aa.Nsuu bahaanaa manaa hai
aur agar aa.Nsuu bahaaye.n bhii to vo dekhe.nge kyo.n?
aah bharanaa shor karanaa gul machaanaa manaa hai
gul machaayaa bhii to matalab kis tarah samajhe.nge vo
haay ! matalab saaf-saaf un ko bataanaa manaa hai
aur agar matalab bataayaa to bhii to vo de.nge javaab
dil lagaayaa tum ne kyo.n jab dil lagaanaa manaa hai

dil kaa na kahaa maanaa 
e yaar
dil kaa na kahaa maanaa gaddaar huii aa.Nkhe.n

gaddaar huii aa.Nkhe.n laachaar huii aa.Nkhe.n
achchhaa unhe.n dekhaa hai laachaar huii aa.Nkhe.n
laachaar huii aa.Nkhe.n mayaKvaar huii aa.Nkhe.n
achchhaa unhe.n dekhaa hai mayaKvaar huii aa.Nkhe.n
mayaKvaar huii aa.Nkhe.n gul_naar huii aa.Nkhe.n
achchhaa unhe.n dekhaa hai gul_naar huii aa.Nkhe.n
gul_naar huii aa.Nkhe.n sarashaar huii aa.Nkhe.n
achchhaa unhe.n dekhaa hai sarashaar huii aa.Nkhe.n

achchhaa unhe.n dekhaa hai

**Comment by morosebose** [comment]
I'd never heard (of) this song before. Can't say that my life has been deeply enriched by the experience of hearing it. Nevertheless, file edited, commit made, PR issued.

**Comment by v9y** [comment]
This got good air time on radio when I was growing up. I rather like the song. It reminds me of Haqeeqat's 'hoke majabuur mujhe'.

**Comment by morosebose** [comment]
Interesting. I remember the other songs of Shankar Hussain getting a lot of airtime ("apane-aap raato.n me.n", "aap yuu.N faasalo.n se", and particularly "kahii.n ek maasuum naazuk-sii la.Dakii") but this one, not at all.
